export const ApplicationsData = [
  {
    id: 1,
    title: "Frontend Engineer",
    company: "Tech Corp",
    status: "Applied",
    appliedDate: "2025-12-01",
    rejectionReason: "",
  },
  {
    id: 2,
    title: "Backend Engineer",
    company: "Code Labs",
    status: "Rejected",
    appliedDate: "2025-11-28",
    rejectionReason: "Lack of experience in Node.js",
  },
  {
    id: 3,
    title: "Full Stack Developer",
    company: "Innovate Ltd",
    status: "Accepted",
    appliedDate: "2025-12-05",
    rejectionReason: "",
  },
  {
    id: 4,
    title: "DevOps Engineer",
    company: "CloudWorks",
    status: "Completed",
    appliedDate: "2025-10-20",
    rejectionReason: "",
  },
  {
    id: 5,
    title: "UI/UX Designer",
    company: "Creative Minds",
    status: "Applied",
    appliedDate: "2025-12-10",
    rejectionReason: "",
  },
  {
    id: 6,
    title: "Mobile App Developer",
    company: "Appify",
    status: "Rejected",
    appliedDate: "2025-11-30",
    rejectionReason: "Insufficient React Native experience",
  },
];
