import type { ManageGroups } from "@/pages/admin/manage_groups/type";

export interface DetailsTypes {
  name: string;
  phone: string;
  email: string;
}

export interface SelectEngineerProps {
  id: number;
  engineerID: number | string;
  details: DetailsTypes;    
  tenancy: string;
  role: string;
  level: string;
  skills: string[];
  documents: string;
  location: string;
  registrationDate: string;
  walletBalance: string;
  kycStatus: string;
  employmentStatus: string;
  avgRating: number;
  approvalStatus: string;
}

export const manageGroups: ManageGroups[] = [
  {
    srNo: 1,
    groupName: "Electrical Team",
    groupDescription: "Handles all electrical work orders",
    noOfEngineers: 12,
    createdDate: "2025-08-12",
    createdBy: "Admin",
    updatedDate: "2025-10-25",
    updatedBy: "Admin",
    status: false,
  },
  {
    srNo: 2,
    groupName: "Plumbing Crew",
    groupDescription: "Plumbing & water line repair experts",
    noOfEngineers: 8,
    createdDate: "2025-07-12",
    createdBy: "Admin",
    updatedDate: "2025-09-25",
    updatedBy: "Admin",
    status: true,
  },
  {
    srNo: 3,
    groupName: "Senior Engineers",
    groupDescription: "Experienced engineers assigned to critical tasks",
    noOfEngineers: 10,
    createdDate: "2025-09-18",
    createdBy: "Admin",
    updatedDate: "2025-10-27",
    updatedBy: "Admin",
    status: true,
  },
  {
    srNo: 4,
    groupName: "Field Team – North Zone",
    groupDescription: "Engineers for north region field operations",
    noOfEngineers: 17,
    createdDate: "2025-05-15",
    createdBy: "Admin",
    updatedDate: "2025-10-20",
    updatedBy: "Admin",
    status: false,
  },
  {
    srNo: 5,
    groupName: "Onboarding Training Batch",
    groupDescription: "Newly joined engineers under training",
    noOfEngineers: 22,
    createdDate: "2025-08-12",
    createdBy: "Admin",
    updatedDate: "2025-11-25",
    updatedBy: "Admin",
    status: true,
  },
  {
    srNo: 6,
    groupName: "Team A",
    groupDescription: "Handles all electrical work orders",
    noOfEngineers: 12,
    createdDate: "2025-06-10",
    createdBy: "Admin",
    updatedDate: "2025-11-25",
    updatedBy: "Admin",
    status: true,
  },
  {
    srNo: 7,
    groupName: "Team B",
    groupDescription: "Handles all electrical work orders",
    noOfEngineers: 12,
    createdDate: "2025-08-18",
    createdBy: "Admin",
    updatedDate: "2025-10-28",
    updatedBy: "Admin",
    status: false,
  },
  {
    srNo: 8,
    groupName: "Team C",
    groupDescription: "Handles all electrical work orders",
    noOfEngineers: 12,
    createdDate: "2025-04-12",
    createdBy: "Admin",
    updatedDate: "2025-10-21",
    updatedBy: "Admin",
    status: true,
  },
  {
    srNo: 9,
    groupName: "Main Team",
    groupDescription: "Handles all electrical work orders",
    noOfEngineers: 12,
    createdDate: "2025-02-15",
    createdBy: "Admin",
    updatedDate: "2025-10-22",
    updatedBy: "Admin",
    status: true,
  },
  {
    srNo: 10,
    groupName: "Painting Team",
    groupDescription: "Handles all electrical work orders",
    noOfEngineers: 12,
    createdDate: "2025-04-10",
    createdBy: "Admin",
    updatedDate: "2025-10-30",
    updatedBy: "Admin",
    status: true,
  },
];

export const SelectEngineer: SelectEngineerProps[] = [
  {
    id: 1,
    engineerID: "ENG-1001",
    details: { name: "Alice Johnson", phone: "+91 98765 43210", email: "alice.johnson@example.com" },
    documents: "View",
    location: "Mumbai, India",
    registrationDate: "2024-02-15",
    walletBalance: "₹2,500",
    kycStatus: "Verified",
    employmentStatus: "Active",
    avgRating: 4.7,
    approvalStatus: "Approved",
    skills: ["React", "Node.js"],
    level: "Senior",
    role: "Software Engineer",
    tenancy: "Client A",
  },
  {
    id: 2,
    engineerID: "ENG-1002",
    details: { name: "Brian Lee", phone: "+91 98765 43211", email: "brian.lee@example.com" },
    documents: "View",
    location: "Pune, India",
    registrationDate: "2024-03-10",
    walletBalance: "₹1,200",
    kycStatus: "Pending",
    employmentStatus: "Inactive",
    avgRating: 3.9,
    approvalStatus: "Under Review",
    skills: ["Python", "Django"],
    level: "Junior",
    role: "Backend Engineer",
    tenancy: "Client B",
  },
  {
    id: 3,
    engineerID: "ENG-1003",
    details: { name: "Chloe Smith", phone: "+91 95765 43210", email: "chloe.smith@example.com" },
    documents: "View",
    location: "Bangalore, India",
    registrationDate: "2024-05-21",
    walletBalance: "₹4,800",
    kycStatus: "Verified",
    employmentStatus: "Active",
    avgRating: 4.5,
    approvalStatus: "Approved",
    skills: ["React", "DevOps"],
    level: "Lead",
    role: "Full Stack Engineer",
    tenancy: "Client C",
  },
  {
    id: 4,
    engineerID: "ENG-1004",
    details: { name: "Arjun Mehta", phone: "+91 98765 43212", email: "arjun.mehta@example.com" },
    documents: "View",
    location: "Delhi, India",
    registrationDate: "2024-06-30",
    walletBalance: "₹3,100",
    kycStatus: "Rejected",
    employmentStatus: "Suspended",
    avgRating: 3.4,
    approvalStatus: "Rejected",
    skills: ["Angular", "Node.js"],
    level: "Mid",
    role: "Frontend Engineer",
    tenancy: "Client A",
  },
  {
    id: 5,
    engineerID: "ENG-1005",
    details: { name: "Emily Davis", phone: "+91 98765 43213", email: "emily.davis@example.com" },
    documents: "View",
    location: "Hyderabad, India",
    registrationDate: "2024-07-14",
    walletBalance: "₹6,000",
    kycStatus: "Verified",
    employmentStatus: "Active",
    avgRating: 4.9,
    approvalStatus: "Approved",
    skills: ["React", "Python"],
    level: "Senior",
    role: "Full Stack Engineer",
    tenancy: "Client B",
  },
  {
    id: 6,
    engineerID: "ENG-1006",
    details: { name: "David Kumar", phone: "+91 98765 43214", email: "david.kumar@example.com" },
    documents: "View",
    location: "Chennai, India",
    registrationDate: "2024-08-01",
    walletBalance: "₹2,900",
    kycStatus: "Verified",
    employmentStatus: "Active",
    avgRating: 4.2,
    approvalStatus: "Approved",
    skills: ["Node.js", "DevOps"],
    level: "Mid",
    role: "Backend Engineer",
    tenancy: "Client C",
  },
  {
    id: 7,
    engineerID: "ENG-1007",
    details: { name: "Fiona Patel", phone: "+91 98765 43215", email: "fiona.patel@example.com" },
    documents: "View",
    location: "Kolkata, India",
    registrationDate: "2024-09-12",
    walletBalance: "₹5,500",
    kycStatus: "Verified",
    employmentStatus: "Active",
    avgRating: 4.6,
    approvalStatus: "Approved",
    skills: ["React", "Angular"],
    level: "Senior",
    role: "Frontend Engineer",
    tenancy: "Client A",
  },
];
