import type { ManageGroups } from "@/pages/admin/manage_groups/type";

export const manageGroups: ManageGroups[] = [
  {
    srNo: 1,
    groupName: "Electrical Team",
    groupDescription: "Handles all electrical work orders",
    noOfEngineers: 12,
    createdDate: "2025-08-12",
    createdBy: "Admin",
    updatedDate: "2025-10-25",
    updatedBy: "Admin",
    status: false,
  },
  {
    srNo: 2,
    groupName: "Plumbing Crew",
    groupDescription: "Plumbing & water line repair experts",
    noOfEngineers: 8,
    createdDate: "2025-08-12",
    createdBy: "Admin",
    updatedDate: "2025-10-25",
    updatedBy: "Admin",
    status: true,
  },
  {
    srNo: 3,
    groupName: "Senior Engineers",
    groupDescription: "Experienced engineers assigned to critical tasks",
    noOfEngineers: 10,
    createdDate: "2025-08-12",
    createdBy: "Admin",
    updatedDate: "2025-10-25",
    updatedBy: "Admin",
    status: true,
  },
  {
    srNo: 4,
    groupName: "Field Team – North Zone",
    groupDescription: "Engineers for north region field operations",
    noOfEngineers: 17,
    createdDate: "2025-08-12",
    createdBy: "Admin",
    updatedDate: "2025-10-25",
    updatedBy: "Admin",
    status: false,
  },
  {
    srNo: 5,
    groupName: "Onboarding Training Batch",
    groupDescription: "Newly joined engineers under training",
    noOfEngineers: 22,
    createdDate: "2025-08-12",
    createdBy: "Admin",
    updatedDate: "2025-10-25",
    updatedBy: "Admin",
    status: true,
  },
  {
    srNo: 6,
    groupName: "Team A",
    groupDescription: "Handles all electrical work orders",
    noOfEngineers: 12,
    createdDate: "2025-08-12",
    createdBy: "Admin",
    updatedDate: "2025-10-25",
    updatedBy: "Admin",
    status: true,
  },
  {
    srNo: 7,
    groupName: "Team B",
    groupDescription: "Handles all electrical work orders",
    noOfEngineers: 12,
    createdDate: "2025-08-12",
    createdBy: "Admin",
    updatedDate: "2025-10-25",
    updatedBy: "Admin",
    status: false,
  },
  {
    srNo: 8,
    groupName: "Team C",
    groupDescription: "Handles all electrical work orders",
    noOfEngineers: 12,
    createdDate: "2025-08-12",
    createdBy: "Admin",
    updatedDate: "2025-10-25",
    updatedBy: "Admin",
    status: true,
  },
  {
    srNo: 9,
    groupName: "Main Team",
    groupDescription: "Handles all electrical work orders",
    noOfEngineers: 12,
    createdDate: "2025-08-12",
    createdBy: "Admin",
    updatedDate: "2025-10-25",
    updatedBy: "Admin",
    status: true,
  },
  {
    srNo: 10,
    groupName: "Painting Team",
    groupDescription: "Handles all electrical work orders",
    noOfEngineers: 12,
    createdDate: "2025-08-12",
    createdBy: "Admin",
    updatedDate: "2025-10-25",
    updatedBy: "Admin",
    status: true,
  },
];
