import type { ManageClientProps } from "@/pages/admin/client";

export const manageClient: ManageClientProps[] = [
  {
    id: 1,
    clientID: "CLT-001",
    details: "Corporate client specializing in renewable energy solutions.",
    documents: "View",
    location: "Mumbai, India",
    registrationDate: "2024-02-12",
    walletBalance: "₹12,500",
    kycStatus: "Verified",
    approvalStatus: "Approved",
  },
  {
    id: 2,
    clientID: "CLT-002",
    details: "Small business owner operating a chain of electronics stores.",
    documents: "View",
    location: "Delhi, India",
    registrationDate: "2024-03-08",
    walletBalance: "₹3,200",
    kycStatus: "Pending",
    approvalStatus: "Under Review",
  },
  {
    id: 3,
    clientID: "CLT-003",
    details: "Startup focused on smart home automation systems.",
    documents: "View",
    location: "Bangalore, India",
    registrationDate: "2024-05-20",
    walletBalance: "₹8,750",
    kycStatus: "Verified",
    approvalStatus: "Approved",
  },
  {
    id: 4,
    clientID: "CLT-004",
    details: "Freelancer working as an independent electrical consultant.",
    documents: "View",
    location: "Pune, India",
    registrationDate: "2024-07-01",
    walletBalance: "₹1,450",
    kycStatus: "Rejected",
    approvalStatus: "Suspended",
  },
  {
    id: 5,
    clientID: "CLT-005",
    details: "Construction firm managing multiple large-scale projects.",
    documents: "View",
    location: "Hyderabad, India",
    registrationDate: "2024-09-10",
    walletBalance: "₹15,000",
    kycStatus: "Verified",
    approvalStatus: "Approved",
  },
];
