export const JOB_TAB_LABELS = {
  timeline: "Timeline",
  jobOverview: "Job Overview",
  workLocation: "Work Location",
  logs: "Logs",
  workSubmissions: "Work Submissions",
  jobInformation: "Job Information",
  requirement: "Requirement",
  spocDetails: "SPOC Details",
  other: "Other",
  terms: "Proposal's Terms & Conditions",
  manageProposals: "Manage Proposals",
  proposalInfo: "Proposal Info",
};

export const JOB_TAB_COPY = {
  sectionTitle: "Please fill these details",
  proposalDescriptionAndAttachments: "Proposal Description and Attachments",
  proposalDescriptionLabel: "Proposal Description",
  proposalDescriptionPlaceholder: "Write your proposal...",
  proposalDescriptionRequired: "Proposal description is required",
  attachmentsLabel: "Attachments (Cover Letter, Docs etc.)",
  reviewProposal: "Review Proposal",
  sendProposalTitle: "Send Proposal",
  attachmentsTitle: "Attachments",
  totalProposalsLabel: "Total Proposals",
  receivedOnPrefix: "Received On: ",
  sentOnPrefix: "Sent On: ",
  acceptProposalTitle: "Accept Proposal",
  acceptProposalBody: "Are you sure you want to accept this proposal?",
  rejectProposalTitle: "Reject Proposal",
  rejectProposalBody: "Are you sure you want to reject this proposal?",
  cancel: "Cancel",
  editDetails: "Edit Details",
  submitProposal: "Submit Proposal",
  proposalAccepted: "Proposal accepted successfully!",
  proposalRejected: "Proposal rejected successfully",
  allProcessed: "All proposals have been processed.",
  successMessage: "Proposal has been sent successfully",
  reject: "Reject",
  viewProfile: "View Profile",
  accept: "Accept",
};

export const JOB_TAB_CONFIG = {
  fileUpload: {
    accept: ".pdf",
    maxPages: 5,
  },
  successDelayMs: 4000,
  defaultSentOn: "05 Apr 2026, 1:05PM",
};
