export const EngineersList = [
  {
    id: 1,
    name: "Alice Johnson",
    ratings: "4.5",
    designation: "Senior Developer",
    reviewCount: 10,
    role: "Full-Stack Developer",
  },
  {
    id: 2,
    name: "Michael Smith",
    ratings: "4.2",
    designation: "Project Manager",
    reviewCount: 5,
    role: "Project Manager",
  },
  {
    id: 3,
    name: "Sofia Martinez",
    ratings: "4.8",
    designation: "UI/UX Designer",
    reviewCount: 8,
    role: "UI/UX Designer",
  },
  {
    id: 4,
    name: "David Lee",
    ratings: "4.1",
    designation: "Software Engineer",
    reviewCount: 3,
    role: "Software Engineer",
  },
  {
    id: 5,
    name: "Priya Sharma",
    ratings: "4.7",
    designation: "Business Analyst",
    reviewCount: 7,
    role: "Business Analyst",
  },
  {
    id: 6,
    name: "John Williams",
    ratings: "4.3",
    designation: "QA Engineer",
    reviewCount: 3,
    role: "QA Engineer",
  },
  {
    id: 7,
    name: "Emma Brown",
    ratings: "4.9",
    designation: "Product Owner",
    reviewCount: 9,
    role: "Product Owner",
  },
  {
    id: 8,
    name: "Arjun Patel",
    ratings: "4.4",
    designation: "DevOps Engineer",
    reviewCount: 4,
    role: "DevOps Engineer",
  },
  {
    id: 9,
    name: "Chloe Kim",
    ratings: "4.6",
    designation: "Scrum Master",
    reviewCount: 6,
    role: "Scrum Master",
  },
  {
    id: 10,
    name: "Lucas Green",
    ratings: "4.0",
    designation: "Intern",
    reviewCount: 0,
    role: "Intern",
  },
];

export const ProposalsList = [
  {
    id: 1,
    engineerName: "alex_dev",
    ratings: "4.6",
    reviewCount: "10",
    bitAmount: "250",
    payType: "Hourly",
    availability: "Immediate",
    jobID: 1,
    jobName: "Software Engineer",
    proposal:
      "I have 5 years of experience in React and can deliver this project quickly.",
    portfolioDoc: "portfolio_alex.pdf",
  },
  {
    id: 2,
    engineerName: "sophia_design",
    ratings: "4.8",
    reviewCount: "5",
    bitAmount: "500",
    payType: "Fixed",
    availability: "Immediate",
    jobID: 2,
    jobName: "Python Engineer",
    proposal:
      "I specialize in clean UI/UX and will provide multiple design iterations.",
    portfolioDoc: "sophia_ui_portfolio.pdf",
  },
  {
    id: 3,
    engineerName: "michael_codes",
    ratings: "4.4",
    bitAmount: "300",
    reviewCount: "3",
    payType: "Hourly",
    availability: "Immediate",
    jobID: 3,
    jobName: "Project Manager",
    proposal:
      "Experienced in Node.js, Express, and databases. Ready to start immediately.",
    portfolioDoc: "michael_backend_work.zip",
  },
  {
    id: 4,
    engineerName: "priya_writer",
    ratings: "4.9",
    bitAmount: "150",
    reviewCount: "2",
    payType: "Fixed",
    availability: "Immediate",
    jobID: 4,
    jobName: "Senior Product Designer",
    proposal:
      "I provide SEO-optimized, high-quality content with fast turnaround.",
    portfolioDoc: "priya_writing_samples.docx",
  },
  {
    id: 5,
    engineerName: "daniel_tech",
    ratings: "4.2",
    bitAmount: "200",
    reviewCount: "4",
    payType: "Hourly",
    availability: "Immediate",
    jobID: 6,
    jobName: "Junior Web Designer",
    proposal: "I can set up CI/CD pipelines and manage cloud deployment.",
    portfolioDoc: "daniel_devops_portfolio.pdf",
  },
];
