import type { NotificationProps } from "@/pages/engineer/account_settings/types";

export const mockNotifications: NotificationProps[] = [
  {
    id: 1,
    type: "job_offer",
    title: "You Received a Job Offer!",
    message:
      "Your proposal has been reviewed, and you’ve been selected for the role.",
    jobTitle: "Angular Developer",
    location: "San Francisco, CA",
    client: "TechNova Co",
    payment: "$3,000 Fixed",
    duration: "2 Weeks",
    timestamp: "1h",
    requiresConfirmation: true,
    confirmationStatus: "pending",
    icon: "📬",
    read: false,
  },
  {
    id: 2,
    type: "invitation",
    title: "Invited for Job",
    message: "Nick John invited you to apply for a new job.",
    timestamp: "2h",
    icon: "📩",
    read: false,
  },
  {
    id: 3,
    type: "revision",
    title: "Revision Requested",
    message: "Client requested a revision on your submission.",
    timestamp: "3h",
    icon: "✏️",
    read: true,
  },
  {
    id: 4,
    type: "payment_released",
    title: "Payment Released",
    message: "Your payment has been released to your wallet.",
    timestamp: "4h",
    icon: "💰",
    read: true,
  },
  {
    id: 5,
    type: "withdrawal",
    title: "Withdrawal Successful",
    message: "Funds have been transferred to your bank account.",
    timestamp: "5h",
    icon: "🏦",
    read: true,
  },
  {
    id: 6,
    type: "proposal_received",
    title: "New Proposal Received",
    message: "A client sent you a new proposal.",
    timestamp: "6h",
    icon: "📄",
    read: false,
  },
  {
    id: 7,
    type: "application_viewed",
    title: "Application Viewed",
    message: "A client viewed your job application.",
    timestamp: "7h",
    icon: "👀",
    read: true,
  },
  {
    id: 8,
    type: "view",
    title: "Profile Viewed",
    message: "Someone viewed your profile.",
    timestamp: "8h",
    icon: "👤",
    read: true,
  },
  {
    id: 9,
    type: "job_offer",
    title: "Job Offer Received",
    message: "You received a new job offer for a React project.",
    jobTitle: "React Developer",
    timestamp: "9h",
    requiresConfirmation: true,
    confirmationStatus: "pending",
    icon: "📬",
    read: false,
  },
  {
    id: 10,
    type: "invitation",
    title: "Job Invitation",
    message: "You were invited to apply for a backend role.",
    timestamp: "10h",
    icon: "📩",
    read: true,
  },
  {
    id: 11,
    type: "revision",
    title: "Revision Needed",
    message: "Minor updates are required before approval.",
    timestamp: "11h",
    icon: "✏️",
    read: true,
  },
  {
    id: 12,
    type: "payment_released",
    title: "Milestone Payment Released",
    message: "Milestone payment has been added to your wallet.",
    timestamp: "12h",
    icon: "💰",
    read: true,
  },
  {
    id: 13,
    type: "withdrawal",
    title: "Withdrawal Completed",
    message: "Withdrawal processed successfully.",
    timestamp: "13h",
    icon: "🏦",
    read: true,
  },
  {
    id: 14,
    type: "proposal_received",
    title: "Proposal Arrived",
    message: "A new project proposal has been received.",
    timestamp: "14h",
    icon: "📄",
    read: false,
  },
  {
    id: 15,
    type: "application_viewed",
    title: "Application Viewed",
    message: "Your application was reviewed by the client.",
    timestamp: "15h",
    icon: "👀",
    read: true,
  },
  {
    id: 16,
    type: "view",
    title: "Job Viewed",
    message: "Your posted job was viewed by freelancers.",
    timestamp: "16h",
    icon: "👁️",
    read: true,
  },
  {
    id: 17,
    type: "job_offer",
    title: "Offer for UI Designer",
    message: "You received an offer for a UI/UX design project.",
    jobTitle: "UI Designer",
    timestamp: "17h",
    requiresConfirmation: true,
    confirmationStatus: "pending",
    icon: "📬",
    read: false,
  },
  {
    id: 18,
    type: "invitation",
    title: "Project Invitation",
    message: "You were invited to join a long-term project.",
    timestamp: "18h",
    icon: "📩",
    read: true,
  },
  {
    id: 19,
    type: "revision",
    title: "Revision Update",
    message: "Client requested another revision.",
    timestamp: "19h",
    icon: "✏️",
    read: false,
  },
  {
    id: 20,
    type: "payment_released",
    title: "Final Payment Released",
    message: "Final project payment has been released.",
    timestamp: "20h",
    icon: "💰",
    read: true,
  },
  {
    id: 21,
    type: "withdrawal",
    title: "Withdrawal Initiated",
    message: "Your withdrawal request is being processed.",
    timestamp: "21h",
    icon: "🏦",
    read: true,
  },
  {
    id: 22,
    type: "proposal_received",
    title: "New Proposal",
    message: "You received a proposal from a new client.",
    timestamp: "22h",
    icon: "📄",
    read: false,
  },
  {
    id: 23,
    type: "application_viewed",
    title: "Application Seen",
    message: "Your application has been seen by the employer.",
    timestamp: "23h",
    icon: "👀",
    read: true,
  },
  {
    id: 24,
    type: "view",
    title: "Profile View",
    message: "A recruiter viewed your profile.",
    timestamp: "1d",
    icon: "👤",
    read: true,
  },
  {
    id: 25,
    type: "job_offer",
    title: "Backend Developer Offer",
    message: "You received a backend developer job offer.",
    jobTitle: "Node.js Developer",
    timestamp: "1d",
    requiresConfirmation: true,
    confirmationStatus: "pending",
    icon: "📬",
    read: false,
  },
];

export const mockClientNotificationsData: NotificationProps[] = [
  {
    id: 1,
    type: "proposal_received",
    title: "Proposal Received",
    message:
      'Aisha Khan submitted a proposal for "UI Developer – Dashboard Project".',
    timestamp: "1h",
    icon: "⚡",
    read: true,
  },
  {
    id: 2,
    type: "application_viewed",
    title: "Your application Viewed",
    message: "The client has reviewed your proposal.",
    timestamp: "1h",
    icon: "⚡",
    read: true,
  },
  {
    id: 3,
    type: "proposal_received",
    title: "Proposal Received",
    message:
      'Aisha Khan submitted a proposal for "UI Developer – Dashboard Project".',
    timestamp: "2h",
    icon: "⚡",
    read: true,
  },
];
