import type { Job } from "@/pages/engineer/search_result/types";

export const sampleJobs: Job[] = [
  {
    title: "Software Engineer",
    company: "Google",
    companyLogo: "/logos/google.png",
    category: "IT",
    employmentType: "Full-Time",
    type: "on-site",
    id: 1,
    client: "Google",
    time: "8 Hours of Jobs",
    description:
      "Join our dynamic team as a Senior Product Designer where you will lead the design of innovative products. Your role will encompass everything from conceptualization to execution, ensuring a seamless user experience across all platforms.",
    location: "San Francisco, USA",
    salary: "180,000/year",
    postedTime: "30min ago",
    rating: 4,
    experience: 5,
    budgetType: "fixed",
    skills: ["Figma", "Adobe XD", "UI/UX"],
    status: "new",
    startDate: "May 28, 2025, 10:00 AM",
    duration: "8 Hours of Work",
    pay: "400",
    place: "featured",
    isBookmarked: true,
  },
  {
    title: "Python Engineer",
    company: "Facebook",
    companyLogo: "/logos/facebook.png",
    category: "IT",
    employmentType: "Full-Time",
    type: "on-site",
    salary: "180,000/year",
    location: "California, USA",
    id: 2,
    client: "Facebook",
    time: "8 Hours of Jobs",
    description:
      "We are looking for a Junior Web Designer who is passionate about creating engaging and user-friendly websites. You will work alongside our team to assist in developing web interfaces that captivate users and enhance their online experience.",
    postedTime: "30min ago",
    rating: 4,
    experience: 2,
    budgetType: "hourly",
    skills: ["HTML", "CSS", "JavaScript", "UI/UX"],
    status: "new",
    startDate: "May 28, 2025, 10:00 AM",
    duration: "8 Hours of Work",
    pay: "400",
    place: "featured",
  },
  {
    title: "Project Manager",
    company: "Google",
    companyLogo: "/logos/google.png",
    category: "IT",
    employmentType: "Full-Time",
    type: "on-site",
    salary: "180,000/year",
    location: "California, USA",
    id: 3,
    client: "Google",
    time: "10 Hours of Jobs",
    description:
      "test",
    postedTime: "2h ago",
    rating: 5,
    experience: 4,
    budgetType: "fixed",
    skills: ["Python", "Java", "SQL", "AWS"],
    status: "new",
    startDate: "May 28, 2025, 10:00 AM",
    duration: "10 Hours of Work",
    pay: "500",
    place: "featured",
    isBookmarked: true,
  },
  {
    id: 4,
    title: "Senior Product Designer",
    client: "TechNova Co",
    time: "8 Hours of Jobs",
    description:
      "Join our dynamic team as a Senior Product Designer where you will lead the design of innovative products. Your role will encompass everything from conceptualization to execution, ensuring a seamless user experience across all platforms.",
    location: "San Francisco, USA",
    salary: "4000",
    postedTime: "30min ago",
    category: "Designing",
    rating: 4,
    experience: 5,
    budgetType: "fixed",
    skills: ["Figma", "Adobe XD", "UI/UX"],
    status: "applied",
    type: "remote",
    startDate: "May 28, 2025, 10:00 AM",
    duration: "8 Hours of Work",
    pay: "400",
    place: "recommended",
    isBookmarked: true,
  },
  {
    id: 5,
    title: "Looking for a talented graphic designer",
    client: "TechNova Co",
    time: "8 Hours of Jobs",
    description:
      "We are seeking a talented graphic designer with a flair for creativity and a keen eye for detail. This position will focus on reimagining our visual identity and elevating our brand through stunning graphics.",
    location: "San Francisco, USA",
    salary: "4000",
    postedTime: "30min ago",
    category: "Designing",
    rating: 5,
    experience: 3,
    budgetType: "fixed",
    skills: ["PhotoShop", "Illustrator", "Motion Graphics"],
    status: "completed",
    type: "on-site",
    startDate: "May 28, 2025, 10:00 AM",
    duration: "8 Hours of Work",
    pay: "400",
    place: "recommended",
  },
  {
    id: 6,
    title: "Junior Web Designer",
    client: "TechNova Co",
    time: "8 Hours of Jobs",
    description:
      "We are looking for a Junior Web Designer who is passionate about creating engaging and user-friendly websites. You will work alongside our team to assist in developing web interfaces that captivate users and enhance their online experience.",
    location: "Austin, USA",
    salary: "4000",
    postedTime: "30min ago",
    category: "IT",
    rating: 4,
    experience: 2,
    budgetType: "hourly",
    skills: ["HTML", "CSS", "JavaScript", "UI/UX"],
    status: "inprogress",
    type: "on-site",
    startDate: "May 28, 2025, 10:00 AM",
    duration: "8 Hours of Work",
    pay: "400",
    place: "recommended",
    isBookmarked: true,
  },
  {
    id: 7,
    title: "Software Engineer",
    client: "Innovate Tech",
    time: "10 Hours of Jobs",
    description:
      "We're looking for a skilled Software Engineer to join our growing team. You'll be working on cutting-edge applications and collaborating with cross-functional teams to deliver high-quality software solutions.",
    location: "Chennai, India",
    salary: "5000",
    postedTime: "1h ago",
    category: "IT",
    rating: 5,
    experience: 4,
    budgetType: "fixed",
    skills: ["Python", "Java", "SQL", "AWS"],
    status: "new",
    type: "on-site",
    startDate: "May 28, 2025, 10:00 AM",
    duration: "10 Hours of Work",
    pay: "500",
    place: "recommended",
  },
  {
    id: 8,
    title: "Innovate Tech",
    client: "Innovate Tech Co",
    time: "10 Hours of Jobs",
    description:
      "Test2",
    location: "New York, USA",
    salary: "5000",
    postedTime: "2h ago",
    category: "IT",
    rating: 5,
    experience: 4,
    budgetType: "fixed",
    skills: ["Python", "Java", "SQL", "AWS"],
    status: "new",
    type: "on-site",
    startDate: "May 28, 2025, 10:00 AM",
    duration: "10 Hours of Work",
    pay: "500",
    place: "recommended",
  },
  {
    id: 9,
    title: "Innovate Tech",
    client: "Innovate Tech",
    time: "10 Hours of Jobs",
    description:
      "Test3",
    location: "New York, USA",
    salary: "5000",
    postedTime: "2h ago",
    category: "IT",
    rating: 5,
    experience: 4,
    budgetType: "fixed",
    skills: ["Python", "Java", "SQL", "AWS"],
    status: "inprogress",
    type: "on-site",
    startDate: "May 28, 2025, 10:00 AM",
    duration: "10 Hours of Work",
    pay: "500",
    place: "recommended",
  },
  {
    id: 10,
    title: "Senior Product Designer",
    client: "TechNova Co",
    time: "8 Hours of Jobs",
    description:
      "Join our dynamic team as a Senior Product Designer where you will lead the design of innovative products. Your role will encompass everything from conceptualization to execution, ensuring a seamless user experience across all platforms.",
    location: "San Francisco, USA",
    salary: "4000",
    postedTime: "30min ago",
    category: "Designing",
    rating: 4,
    experience: 5,
    budgetType: "fixed",
    skills: ["Figma", "Adobe XD", "UI/UX"],
    status: "offer",
    type: "remote",
    startDate: "May 28, 2025, 10:00 AM",
    duration: "8 Hours of Work",
    pay: "400",
    place: "recommended",
  },
];