import type { Job } from "@/pages/engineer/search_result/types";

export const sampleJobs: Job[] = [
  {
    title: "Software Engineer",
    company: "Google",
    companyLogo: "/logos/google.png",
    category: "IT",
    employmentType: "Full-Time",
    type: "on-site",
    id: 1,
    client: "Google",
    time: "8 Hours of Jobs",
    description:
      "Join our dynamic team as a Senior Product Designer where you will lead the design of innovative products...",
    location: "San Francisco, USA",
    salary: "180,000/year",
    postedTime: "30min ago",
    rating: 4,
    experience: 5,
    budgetType: "fixed",
    skills: ["Figma", "Adobe XD", "UI/UX"],
    tools: ["Figma", "Sketch", "Principle", "Zeplin"],
    status: "new",
    startDate: "December 19, 2025, 12:49 AM",
    duration: "8 Hours of Work",
    pay: "400",
    place: "featured",
    isBookmarked: true,
    languages: "English (Primary)",
    poc: {
      name: "Sarah Mitchell",
      role: "Technical Project Manager",
    },
  },
  {
    title: "Python Engineer",
    company: "Facebook",
    companyLogo: "/logos/facebook.png",
    category: "IT",
    employmentType: "Full-Time",
    type: "on-site",
    salary: "180,000/year",
    location: "California, USA",
    id: 2,
    client: "Facebook",
    time: "8 Hours of Jobs",
    description:
      "We are looking for a Junior Web Designer who is passionate about creating engaging and user-friendly websites...",
    postedTime: "30min ago",
    rating: 4,
    experience: 2,
    budgetType: "hourly",
    skills: ["HTML", "CSS", "JavaScript", "UI/UX"],
    tools: ["VS Code", "Chrome DevTools", "Postman", "Git"],
    status: "new",
    startDate: "January 03, 2026, 19:57 AM",
    duration: "8 Hours of Work",
    pay: "400",
    place: "featured",
    languages: "English (Primary), Spanish (Secondary)",
    poc: {
      name: "Michael Chen",
      role: "Engineering Coordinator",
    },
  },
  {
    title: "Project Manager",
    company: "Google",
    companyLogo: "/logos/google.png",
    category: "IT",
    employmentType: "Full-Time",
    type: "on-site",
    salary: "180,000/year",
    location: "California, USA",
    id: 3,
    client: "Google",
    time: "10 Hours of Jobs",
    description: "test",
    postedTime: "2h ago",
    rating: 5,
    experience: 4,
    budgetType: "fixed",
    skills: ["Python", "Java", "SQL", "AWS"],
    tools: ["Jira", "Confluence", "Slack", "Microsoft Teams", "Trello"],
    status: "new",
    startDate: "December 19, 2025, 01:06 PM",
    duration: "10 Hours of Work",
    pay: "500",
    place: "featured",
    isBookmarked: true,
    languages: "English (Primary), Mandarin (Secondary)",
    poc: {
      name: "Priya Sharma",
      role: "Delivery Manager",
    },
  },
  {
    id: 4,
    title: "Senior Product Designer",
    client: "TechNova Co",
    time: "8 Hours of Jobs",
    description:
      "Join our dynamic team as a Senior Product Designer where you will lead the design of innovative products...",
    location: "San Francisco, USA",
    salary: "4000",
    postedTime: "30min ago",
    category: "Designing",
    rating: 4,
    experience: 5,
    budgetType: "fixed",
    skills: ["Figma", "Adobe XD", "UI/UX"],
    status: "Hold",
    tools: ["Figma", "Miro", "Notion", "Abstract"],
    type: "remote",
    startDate: "December 19, 2025, 4:00 PM",
    duration: "8 Hours of Work",
    pay: "400",
    place: "recommended",
    isBookmarked: true,
    languages: "English (Primary)",
    poc: {
      name: "David Kim",
      role: "Design Operations Lead",
    },
  },
  {
    id: 5,
    title: "Looking for a talented graphic designer",
    client: "TechNova Co",
    time: "8 Hours of Jobs",
    description:
      "We are seeking a talented graphic designer with a flair for creativity and a keen eye for detail...",
    location: "San Francisco, USA",
    salary: "4000",
    postedTime: "30min ago",
    category: "Designing",
    rating: 5,
    experience: 3,
    budgetType: "fixed",
    skills: ["PhotoShop", "Illustrator", "Motion Graphics"],
    status: "Unallocated",
    tools: [
      "Adobe Photoshop",
      "Adobe Illustrator",
      "After Effects",
      "InDesign",
    ],
    type: "on-site",
    startDate: "December 19, 2025, 3:00 PM",
    duration: "8 Hours of Work",
    pay: "400",
    place: "recommended",
    languages: "English (Primary), French (Secondary)",
    poc: {
      name: "Laura Fernandez",
      role: "Creative Coordinator",
    },
  },
  {
    id: 6,
    title: "Junior Web Designer",
    client: "TechNova Co",
    time: "8 Hours of Jobs",
    description:
      "We are looking for a Junior Web Designer who is passionate about creating engaging and user-friendly websites...",
    location: "Austin, USA",
    salary: "4000",
    postedTime: "30min ago",
    category: "IT",
    rating: 4,
    experience: 2,
    budgetType: "hourly",
    skills: ["HTML", "CSS", "JavaScript", "UI/UX"],
    status: "Assigned",
    tools: ["VS Code", "Figma", "GitHub", "BrowserStack"],
    type: "on-site",
    startDate: "December 29, 2025, 4:00 PM",
    duration: "8 Hours of Work",
    pay: "400",
    place: "recommended",
    isBookmarked: true,
    languages: "English (Primary), German (Secondary)",
    poc: {
      name: "Alexander Weber",
      role: "Frontend Coordinator",
    },
  },
  {
    id: 7,
    title: "Software Engineer",
    client: "Innovate Tech",
    time: "10 Hours of Jobs",
    description:
      "We're looking for a skilled Software Engineer to join our growing team...",
    location: "Chennai, India",
    salary: "5000",
    postedTime: "1h ago",
    category: "IT",
    rating: 5,
    experience: 4,
    budgetType: "fixed",
    skills: ["Python", "Java", "SQL", "AWS"],
    tools: ["IntelliJ IDEA", "PyCharm", "Docker", "Kubernetes", "Jenkins"],
    status: "new",
    type: "on-site",
    startDate: "December 19, 2025, 4:00 PM",
    duration: "10 Hours of Work",
    pay: "500",
    place: "recommended",
    languages: "English (Primary), Hindi (Secondary)",
    poc: {
      name: "Anita Desai",
      role: "Technical Delivery Manager",
    },
  },
  {
    id: 8,
    title: "Innovate Tech",
    client: "Innovate Tech Co",
    time: "10 Hours of Jobs",
    description: "Test2",
    location: "New York, USA",
    salary: "5000",
    postedTime: "2h ago",
    category: "IT",
    rating: 5,
    experience: 4,
    budgetType: "fixed",
    skills: ["Python", "Java", "SQL", "AWS"],
    status: "Selected",
    tools: ["Postman", "Swagger", "Jira", "GitLab"],
    type: "on-site",
    startDate: "December 19, 2025, 4:00 PM",
    duration: "10 Hours of Work",
    pay: "500",
    place: "recommended",
    languages: "English (Primary), Portuguese (Secondary)",
    poc: {
      name: "Carlos Silva",
      role: "API Integration Lead",
    },
  },
  {
    id: 9,
    title: "Innovate Tech",
    client: "Innovate Tech",
    time: "10 Hours of Jobs",
    description: "Test3",
    location: "New York, USA",
    salary: "5000",
    postedTime: "2h ago",
    category: "IT",
    rating: 5,
    experience: 4,
    budgetType: "fixed",
    skills: ["Python", "Java", "SQL", "AWS"],
    tools: ["Visual Studio", "Eclipse", "Maven", "SonarQube"],
    status: "inprogress",
    type: "hybrid",
    startDate: "May 28, 2025, 10:00 AM",
    duration: "10 Hours of Work",
    pay: "500",
    place: "recommended",
    languages: "English (Primary)",
    poc: {
      name: "Jennifer Lee",
      role: "Java Platform Coordinator",
    },
  },
  {
    id: 10,
    title: "Senior Product Designer",
    client: "TechNova Co",
    time: "8 Hours of Jobs",
    description:
      "Join our dynamic team as a Senior Product Designer where you will lead the design of innovative products...",
    location: "San Francisco, USA",
    salary: "4000",
    postedTime: "30min ago",
    category: "Designing",
    rating: 4,
    experience: 5,
    budgetType: "fixed",
    skills: ["Figma", "Adobe XD", "UI/UX"],
    tools: ["Figma", "Framer", "Protopie", "Lottie"],
    status: "offer",
    type: "remote",
    startDate: "December 20, 2025, 4:00 PM",
    duration: "8 Hours of Work",
    pay: "400",
    place: "recommended",
    languages: "English (Primary), Japanese (Secondary)",
    poc: {
      name: "Takeshi Yamamoto",
      role: "Senior Design POC",
    },
  },
];
