import type { Job } from "@/pages/client/search_result/types";

export const sampleJobs: Job[] = [
  {
    id: 8,
    title: "Posted -8",
    category: "IT",
    employmentType: "Full-Time",
    type: "on-site",
    client: "TechNova Co",
    time: "8 Hours of Jobs",
    description:
      "Join our dynamic team as a Senior Product Designer where you will lead the design of innovative products. Your role will encompass everything from conceptualization to execution, ensuring a seamless user experience across all platforms.",
    location: "San Francisco, USA",
    salary: "4000",
    postedTime: "30min ago",
    rating: 4,
    experience: 5,
    budgetType: "fixed",
    skills: ["Figma", "Adobe XD", "UI/UX"],
    status: "posted",
    startDate: "05 Jan, 2025, 06:32 PM",
    duration: "8 Hours of Work",
    pay: "400",
    engineers: "4+",
    engineerAvatars: [
      "https://randomuser.me/api/portraits/women/65.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
      "https://randomuser.me/api/portraits/women/44.jpg",
      "https://randomuser.me/api/portraits/men/75.jpg"
    ],
    serviceType: "Web Development",
  },
  {
    id: 9,
    title: "Python Engineer",
    companyLogo: "/logos/facebook.png",
    category: "IT",
    employmentType: "Full-Time",
    type: "on-site",
    salary: "$180,000/year",
    location: "California, USA",
    client: "TechNova Co",
    time: "8 Hours of Jobs",
    description:
      "We are looking for a Junior Web Designer who is passionate about creating engaging and user-friendly websites. You will work alongside our team to assist in developing web interfaces that captivate users and enhance their online experience.",
    postedTime: "30min ago",
    rating: 4,
    experience: 2,
    budgetType: "hourly",
    skills: ["HTML", "CSS", "JavaScript", "UI/UX"],
    status: "inprogress",
    startDate: "05 Jan, 2025, 06:32 PM",
    duration: "8 Hours of Work",
    pay: "400",
    engineers: "4+",
    engineerAvatars: [
      "https://randomuser.me/api/portraits/women/65.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
      "https://randomuser.me/api/portraits/women/44.jpg",
      "https://randomuser.me/api/portraits/men/75.jpg"
    ],
    serviceType: "Web Development",
  },
  {
    id: 10,
    title: "Project Manager",
    company: "Google",
    companyLogo: "/logos/google.png",
    category: "IT",
    employmentType: "Full-Time",
    type: "on-site",
    salary: "$180,000/year",
    location: "California, USA",
    client: "Innovate Tech Co",
    time: "10 Hours of Jobs",
    description:
      "innovate tech is a startup that is looking for a talented software engineer to join our growing team. You'll be working on cutting-edge applications and collaborating with cross-functional teams to deliver high-quality software solutions.",
    postedTime: "2h ago",
    rating: 5,
    experience: 4,
    budgetType: "fixed",
    skills: ["Python", "Java", "SQL", "AWS"],
    status: "completed",
    startDate: "05 Jan, 2025, 06:32 PM",
    duration: "10 Hours of Work",
    pay: "500",
    engineers: "4+",
    engineerAvatars: [
      "https://randomuser.me/api/portraits/women/65.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
      "https://randomuser.me/api/portraits/women/44.jpg",
      "https://randomuser.me/api/portraits/men/75.jpg"
    ],
    serviceType: "Web Development",
  },
  {
    id: 1,
    title: "Senior Product Designer",
    client: "TechNova Co",
    time: "8 Hours of Jobs",
    description:
      "Join our dynamic team as a Senior Product Designer where you will lead the design of innovative products. Your role will encompass everything from conceptualization to execution, ensuring a seamless user experience across all platforms.",
    location: "San Francisco, USA",
    salary: "4000",
    postedTime: "30min ago",
    category: "Designing",
    rating: 4,
    experience: 5,
    budgetType: "fixed",
    skills: ["Figma", "Adobe XD", "UI/UX"],
    status: "posted",
    type: "remote",
    startDate: "05 Jan, 2025, 06:32 PM",
    duration: "8 Hours of Work",
    pay: "400",
    engineers: "4+",
    engineerAvatars: [
      "https://randomuser.me/api/portraits/women/65.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
      "https://randomuser.me/api/portraits/women/44.jpg",
      "https://randomuser.me/api/portraits/men/75.jpg"
    ],
    serviceType: "Web Development",
  },
  {
    id: 2,
    title: "Graphic designer",
    client: "TechNova Co",
    time: "8 Hours of Jobs",
    description:
      "We are seeking a talented graphic designer with a flair for creativity and a keen eye for detail. This position will focus on reimagining our visual identity and elevating our brand through stunning graphics.",
    location: "San Francisco, USA",
    salary: "4000",
    postedTime: "30min ago",
    category: "Designing",
    rating: 5,
    experience: 3,
    budgetType: "fixed",
    skills: ["PhotoShop", "Illustrator", "Motion Graphics"],
    status: "inprogress",
    type: "remote",
    startDate: "05 Jan, 2025, 06:32 PM",
    duration: "8 Hours of Work",
    pay: "400",
    engineers: "4+",
    engineerAvatars: [
      "https://randomuser.me/api/portraits/women/65.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
      "https://randomuser.me/api/portraits/women/44.jpg",
      "https://randomuser.me/api/portraits/men/75.jpg"
    ],
    serviceType: "Web design",
  },
  {
    id: 3,
    title: "Junior Web Designer",
    client: "TechNova Co",
    time: "8 Hours of Jobs",
    description:
      "We are looking for a Junior Web Designer who is passionate about creating engaging and user-friendly websites. You will work alongside our team to assist in developing web interfaces that captivate users and enhance their online experience.",
    location: "Austin, USA",
    salary: "4000",
    postedTime: "30min ago",
    category: "IT",
    rating: 4,
    experience: 2,
    budgetType: "hourly",
    skills: ["HTML", "CSS", "JavaScript", "UI/UX"],
    status: "inprogress",
    type: "on-site",
    startDate: "05 Jan, 2025, 06:32 PM",
    duration: "8 Hours of Work",
    pay: "400",
    engineers: "4+",
    engineerAvatars: [
      "https://randomuser.me/api/portraits/women/65.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
      "https://randomuser.me/api/portraits/women/44.jpg",
      "https://randomuser.me/api/portraits/men/75.jpg"
    ],
    serviceType: "Web design",
  },
  {
    id: 4,
    title: "Testing Engineer",
    client: "Innovate Tech",
    time: "10 Hours of Jobs",
    description:
      "We're looking for a skilled Testing Engineer to join our growing team. You'll be working on cutting-edge applications and collaborating with cross-functional teams to deliver high-quality software solutions.",
    location: "Chennai, India",
    salary: "5000",
    postedTime: "1h ago",
    category: "IT",
    rating: 5,
    experience: 4,
    budgetType: "fixed",
    skills: ["Python", "Java", "SQL", "AWS"],
    status: "posted",
    type: "on-site",
    startDate: "05 Jan, 2025, 06:32 PM",
    duration: "10 Hours of Work",
    pay: "500",
    engineers: "4+",
    engineerAvatars: [
      "https://randomuser.me/api/portraits/women/65.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
      "https://randomuser.me/api/portraits/women/44.jpg",
      "https://randomuser.me/api/portraits/men/75.jpg"
    ],
    serviceType: "Software Testing",
  },
  {
    id: 5,
    title: "Posted -5",
    client: "Innovate Tech Co",
    time: "10 Hours of Jobs",
    description:
      "innovate tech is a startup that is looking for a talented software engineer to join our growing team. You'll be working on cutting-edge applications and collaborating with cross-functional teams to deliver high-quality software solutions.",
    location: "New York, USA",
    salary: "5000",
    postedTime: "2h ago",
    category: "IT",
    rating: 5,
    experience: 4,
    budgetType: "fixed",
    skills: ["Python", "Java", "SQL", "AWS"],
    status: "posted",
    type: "on-site",
    startDate: "05 Jan, 2025, 06:32 PM",
    duration: "10 Hours of Work",
    pay: "500",
    engineers: "4+",
    engineerAvatars: [
      "https://randomuser.me/api/portraits/women/65.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
      "https://randomuser.me/api/portraits/women/44.jpg",
      "https://randomuser.me/api/portraits/men/75.jpg"
    ],
    serviceType: "R&D",
  },
  {
    id: 6,
    title: "Innovate Tech",
    client: "Innovate Tech",
    time: "10 Hours of Jobs",
    description:
      "innovate tech is a startup that is looking for a talented software engineer to join our growing team. You'll be working on cutting-edge applications and collaborating with cross-functional teams to deliver high-quality software solutions.",
    location: "New York, USA",
    salary: "5000",
    postedTime: "2h ago",
    category: "IT",
    rating: 5,
    experience: 4,
    budgetType: "fixed",
    skills: ["Python", "Java", "SQL", "AWS"],
    status: "inprogress",
    type: "on-site",
    startDate: "05 Jan, 2025, 06:32 PM",
    duration: "10 Hours of Work",
    pay: "500",
    engineers: "4+",
    engineerAvatars: [
      "https://randomuser.me/api/portraits/women/65.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
      "https://randomuser.me/api/portraits/women/44.jpg",
      "https://randomuser.me/api/portraits/men/75.jpg"
    ],
    serviceType: "R&D",
  },
  {
    id: 7,
    title: "Senior Product Designer",
    client: "TechNova Co",
    time: "8 Hours of Jobs",
    description:
      "Join our dynamic team as a Senior Product Designer where you will lead the design of innovative products. Your role will encompass everything from conceptualization to execution, ensuring a seamless user experience across all platforms.",
    location: "San Francisco, USA",
    salary: "4000",
    postedTime: "30min ago",
    category: "Designing",
    rating: 4,
    experience: 5,
    budgetType: "fixed",
    skills: ["Figma", "Adobe XD", "UI/UX"],
    status: "hold",
    type: "remote",
    startDate: "05 Jan, 2025, 06:32 PM",
    duration: "8 Hours of Work",
    pay: "400",
    engineers: "4+",
    engineerAvatars: [
      "https://randomuser.me/api/portraits/women/65.jpg",
      "https://randomuser.me/api/portraits/men/32.jpg",
      "https://randomuser.me/api/portraits/women/44.jpg",
      "https://randomuser.me/api/portraits/men/75.jpg"
    ],
    serviceType: "Web design",

  },
];
